In [1]:
import numpy as np

In [2]:
array0 = np.zeros(3, dtype=int)

In [3]:
print(array0)

[0 0 0]


In [4]:
array1 = np.zeros((2,4), dtype=float) #taille 2*4
print(array1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
array2 = np.zeros((2,3), dtype=complex)
print(array2)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [6]:
array3 = np.zeros((4,5,6)) #float par defaut
print(array3)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [7]:
array4 = np.array([1,4,5])
print(array4)

[1 4 5]


In [8]:
array3.dtype

dtype('float64')

In [9]:
array3.shape

(4, 5, 6)

In [10]:
array4[1]

4

In [11]:
array3[0,0,3] = 5
print(array3)

[[[0. 0. 0. 5. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [12]:
vect1 = np.arange(5,10,1)
print(vect1)

[5 6 7 8 9]


In [13]:
vect2 = np.arange(3,10,2)
print(vect2)

[3 5 7 9]


In [14]:
vect3 = np.linspace(2, 5, 10, True)
print(vect3)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


In [16]:
vect4 = np.reshape(vect3,(2,5))
vect5 = np.reshape(vect3, (5,2))
print(vect4)
print(vect5)

[[2.         2.33333333 2.66666667 3.         3.33333333]
 [3.66666667 4.         4.33333333 4.66666667 5.        ]]
[[2.         2.33333333]
 [2.66666667 3.        ]
 [3.33333333 3.66666667]
 [4.         4.33333333]
 [4.66666667 5.        ]]
