In [5]:
import numpy as np

a = np.arange(12)**2 #matrice de carrés parfaits
i = np.array([1,3,8,5]) #indices pour la matrice a
print(a)
print(a[i])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  9 64 25]


In [3]:
j = np.array([[3,4],[9,7]])
print(a[j])

[[ 9 16]
 [81 49]]


In [6]:
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
i = np.array([0,1,2,2])
j = np.array([1,0,3,1])
b[i,j]

array([ 1,  4, 11,  9])

In [8]:
c = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
cond = (c > 5)
c[cond] = 5 #remplace par la valeur 5 tous les éléments de c qui ne respectent pas la condition
print(c)

[[0 1 2 3]
 [4 5 5 5]
 [5 5 5 5]]


In [12]:
resultats = np.array([0.9602, -0.99, 0.2837, 0.9602, 0.7539, -0.1455, -0.99, -0.9111, 0.9602, -0.1455, -0.99, 0.5403, -0.99, 0.9602, 0.2837, -0.99, 0.2837, 0.9602])
cond = (resultats < 0)
resultats[cond] = 0
print(resultats)

[0.9602 0.     0.2837 0.9602 0.7539 0.     0.     0.     0.9602 0.
 0.     0.5403 0.     0.9602 0.2837 0.     0.2837 0.9602]


In [ ]:
temps = np.arange(2, 3.7, 0.1)
indices_max = np.argmax(resultats)

